server:
  port: 8080

spring:
  config:
    import:
      - database-local.properties
      - oauth.properties
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: ${DB.DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    database-platform: ${DB.DIALECT}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH.KAKAO.CLIENT}
            redirect-uri: ${OAUTH.KAKAO.REDIRECT}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    site.ssanta.santa: ${LOGGING_LEVEL:DEBUG}