server:
  port: 8080
  servlet:
    context-path: "/api"

spring:
  application:
    name: santa
  profiles:
    active: ${SPRING_ENV:local}

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
