server:
  port: 8080
  servlet:
    context-path: "/api"

spring:
  application:
    name: santa
  profiles:
    active: ${SPRING_ENV:local}
  data:
    mongodb:
      uri: ${MONGODB.URL}
  jpa:
    properties:
      hibernate.hibernate.default_batch_fetch_size: 100

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
